app/main/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""HTML Form Field.
"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired
import settings


class NameForm(FlaskForm):
    name = StringField(
            'Please input your review to perform sentiment analysis.',
            validators=[DataRequired()]
            )
    submit = SubmitField('Submit')


class SensitivityForm(FlaskForm):
    select_field = SelectField(
            'Select Tuning Parameter',
            choices=[],
            default = settings.DEFAULT_SENSITIVITY_ANALYSIS_DF)
    submit = SubmitField('Go')    
    
    
    

app/__init__.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Application factory function.
"""
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from config import config


bootstrap = Bootstrap()
moment = Moment()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    
    bootstrap.init_app(app)
    moment.init_app(app)
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    return app

app/main/__init__.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Blueprint creation.
"""
from flask import Blueprint


main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Application routes.
"""
from flask import render_template, session, redirect, url_for
from bokeh.embed import components
from . import main
from .forms import SensitivityForm, NameForm
from ..model import Loader, Model_Predictor
from ..sensitivity_analysis import DF_Loader, Plotter
import settings


@main.route('/')
def index():
    return render_template('index.html')
        
@main.route('/model_output/predict', methods=['GET', 'POST'])
def model_predict():
    loader = Loader(
             settings.MODEL_PATH, 
             settings.WORD_TO_INDEX_DICT_PATH, 
             settings.INDEX_TO_WORD_DICT_PATH)
    model_predictor = Model_Predictor(
                      loader, 
                      settings.UNKNOWN_TOKEN,
                      settings.START_TOKEN, 
                      settings.SEQUENCE_LENGTH)
    
    form = NameForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        sa_model_output = model_predictor.predict_with_model(session['name'])
        session['sa_model_output'] = sa_model_output
        return redirect(url_for('.model_predict'))    
    return render_template(
                          'model_template.html', 
                          form=form, 
                          name=session['sa_model_output'])

@main.route('/sensitivity_analysis', methods=['GET', 'POST'])
def sensitivity_analysis():    
    df_loader = DF_Loader(settings.PLOT_DF_PATH)
    df_dict = df_loader.pickle_df_sens_loader()
    df_filenames = df_loader.return_filenames()
    form_choices = [(x.replace('.pickle','') , x.replace('.pickle','')) 
                    for x in df_filenames]
    
    form = SensitivityForm()
    form.select_field.choices = form_choices

    session['sens_param_choice'] = form.select_field.data        
    df_plot_input = df_dict[session['sens_param_choice']]    
    plotter = Plotter(
              df_plot_input, 
              settings.SENSITIVITY_PLOT_TITLE,
              settings.PARAM_FEATURE_NAME,
              settings.ACC_FEATURE_NAME)
    
    plot_sens = plotter.create_plot()    
    script, div = components(plot_sens)
    return render_template(
                           'sensitivity_analysis.html',
                           form=form,
                           script=script,
                           div=div)
   

    

    

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='nn.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='nn.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Home</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.model_predict') }}">Model</a></li>
                <li><a href="{{ url_for('main.sensitivity_analysis') }}">Sensitivity Analysis</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Flasky{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1> Welcome to the Sentiment Analysis Flask App! </h1>
</div>

<h1> <font size="6" color="grey" text-align="center" style="font-family:courier"> Please use tabs to navigate through app. </font> </h1>

{% endblock %}

app/templates/model_template.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{% if name %}{{ name }}{% else %}Welcome to the Sentiment Analysis Page{% endif %}!</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/sensitivity_analysis.html
{% import "bootstrap/wtf.html" as wtf %}

<html>
<head>
<link
    href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.14.min.css"
    rel="stylesheet" type="text/css">
<link
    href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.14.min.css"
    rel="stylesheet" type="text/css">

<script src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.14.min.js"></script>
<script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.14.min.js"></script>

</head>
<body>
<H1>Parameter Sensitivity Analysis</H1>

{{ wtf.quick_form(form) }}

{{ script|safe }}
{{ div|safe }}


</body>
</html>